packages:
  - "packages/*"
"overrides":
  "vite": "catalog:"
  "vitest": "catalog:"
  "fvtt-types": "catalog:"
  "@types/node": "catalog:"
catalog:
  vite: "8.1.5"
  vitest: "^4.1.10"
  "fvtt-types": "github:League-of-Foundry-Developers/foundry-vtt-types#77a574469196663030e1c4fccef597a9c1e1e473"
  "@types/node": "24.13.3"
allowBuilds:
  "git@git+https://github.com/league-of-foundry-developers/foundry-vtt-types.git": true
  "@swc/core": true
  classic-level: true
  esbuild: true
blockExoticSubdeps: false
