packages:
  - "packages/*"
"overrides":
  "vite": "catalog:"
  "vitest": "catalog:"
  "fvtt-types": "catalog:"
  "@types/node": "catalog:"
catalog:
  vite: "8.2.2"
  vitest: "^4.1.11"
  "fvtt-types": "github:League-of-Foundry-Developers/foundry-vtt-types#4035705e3c7b2cf817af6b12ff83ed6977979886"
  "@types/node": "24.13.3"
allowBuilds:
  "@league-of-foundry-developers/foundry-vtt-types@git+https://github.com/League-of-Foundry-Developers/foundry-vtt-types.git": true
  "@swc/core": true
  classic-level: true
  esbuild: true
blockExoticSubdeps: false
